#---Database Settings---
mysqlHostName: localhost
mysqlPort: 3306
mysqlUsername: root
mysqlPassword:
mysqlDatabase: EtherMarket

#---General Settings---
#Excessive debug logging? Please use this and post your console log when asking for help
debugenabled: false
#Adds a "Purchased from [username]" lore to valuable, unstackable items that are bought through the shops
item-receipt: true
item-receipt-text: Purchased from
#Logs every transaction in the database
log-transactions: true

#---DATA---
#Changing these WILL cause problems if shops and ATMs have been created
sign-header: [Shop]

#---Enchantment Names---
ARROW_DAMAGE: Power
ARROW_FIRE: Flame
ARROW_INFINITE: Infinity
ARROW_KNOCKBACK: Punch
DAMAGE_ALL: Sharpness
DAMAGE_ARTHROPODS: Bane of Arthropods
DAMAGE_UNDEAD: Smite
DEPTH_STRIDER: Depth Strider
DIG_SPEED: Efficiency
DURABILITY: Unbreaking
FIRE_ASPECT: Fire Aspect
KNOCKBACK: Knockback
LOOT_BONUS_BLOCKS: Fortune
LOOT_BONUS_MOBS: Looting
LUCK: Luck of the Sea
LURE: Lure
OXYGEN: Respiration
PROTECTION_ENVIRONMENTAL: Protection
PROTECTION_EXPLOSIONS: Blast Protection
PROTECTION_FALL: Feather Falling
PROTECTION_FIRE: Fire Protection
PROTECTION_PROJECTILE: Projectile Protection
SILK_TOUCH: Silk Touch
THORNS: Thorns
WATER_WORKER: Aqua Affinity

#--Messages---
#Success Messages
begin-making-shop: Hit the shop with the item you want to sell.
shop-established: Shop has been established!
destroy-again: Destroy the sign again to confirm destruction.
destroy-success: Shop destroyed!
stock-success: Shop stock adjusted!
#Error Messages
already-making-shop: Finish making your other shop before attempting to create another one.
finish-other-shop: Finish making your shop before conducting a transaction.
incorrect-syntax: The buyline was written incorrectly. Please try again.
shop-being-made: Someone is making a shop here. You cannot destroy it.
shop-is-owned: You cannot destroy someone else's shop.
not-sneaking: You must be sneaking to destroy a shop.
no-permission-creation: You do not have permission to make a shop.
no-permission-setstock: You do not have permission to adjust a shop's stock.
not-exist: This shop does not exist.
invalid-item: You cannot sell this.
attached-shop: That block is attached to a shop.
syntax-setstock: /ethermarket setstock <number>
look-at-sign: You must be looking at a shop to use this command.