main: tech.relativelyobjective.ethermarket.EtherMarket
version: 1.5
name: EtherMarket
author: ReltivlyObjectv
depend: [Vault]
commands:
    ethermarket:
        description: Admin command for EtherMarket
        aliases: [em]
permissions:
    ethermarket.admin.destroyothershop: #Allows the destruction of someone else's shop
        default: op
    ethermarket.admin.setstock: #Allows the manual adjusting of a shop's stock
        default: op
    ethermarket.player.makeshop: #Allows the creation of a shop
        default: true